#[[plugins]]
#  package = "netlify-plugin-lunr-indexer"
#    [plugins.inputs]
#    jsonPath = "dist/contents/" # Chemin vers vos données JSON
#    indexPath = "dist/index/full-search.json" # Chemin de sortie de l'index

[[headers]]
  for = "/*"
  [header.values]
    X-Frame-Options= "ALLOWALL"
  
  for = "/.netlify/functions/*"  
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "./dist/functions"
  publish = "./dist" 
  command = "npm i"

[build.environment]
  NODE_VERSION = "20.11.0"

[functions]
  directory = "./dist/functions"
